sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start"
  - docker build -t 1224chopper/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true 1224chopper/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-921466450748"
  bucket_path: "docker-react-app"
  on:
    branch: master
